data:
  action: "select"
  source_table: "CardCreditInfo"
  limit: 100
  filters: {}
  order_by: []
  do_sample: False
  sample_size: 100

preprocess:
  exclude_columns: []
  imputation_neighbors: 5
  threshold_percentage: 0.2

graph:
  node_identifier: ""
  edge_threshold: 0.8

risk:
  method: "max"
  alpha: 1.0
  beta: 1.0
  top_percent: 5.0